### ISSUE TITLE
Request to add Support for DHCP Server Options

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xDhcpServer#11]
Is there a plan to support configuring DHCP server options as opposed to scope options?

**Comment by KarolKaczmarek** [comment]
@HemantMahawar

**Comment by iainbrighton** [comment]
@PlagueHO I'm confused by the resource naming - shouldn't it be xDhcpServerScopeOption. I'll have a look at this...

**Comment by iainbrighton** [comment]
Looks like, that if we don't specify a ScopeId that will set server options. However, the ScopeID is a key...

We could use a special 'ScopeID' name/value to signify that we want to configure server options, i.e.
```powershell
xDhcpServerOption 'SetsServerOptionNotScope' {
    ScopeID = 'Server'
    Router = '192.168.1.254'
}
```
Thoughts @PlagueHO @KarolKaczmarek @HemantMahawar ?

**Comment by PlagueHO** [comment]
My 2c:
@iainbrighton - it is definitely a real pity about the naming of this resource - it is counter intuitive - and makes it pretty difficult to create the Server level resource without confusing things even more. However, what would be consequences of correcting this name? @KarolKaczmarek - is this something that could be considered?

If the name can't be changed:
Your solution would solve the issue of setting server level options it would still leave reservation level options out in the cold. It would be awesome if there was a resource that could manage all three types (server, scope, reservation - I'm ignoring policy options though :smile:). I'm just not sure it is possible with a single resource.

The existing resource can't be used to set any other options either (option 67 on a WDS server anyone?) - if there was a possibility of re-engineering this resource it might be useful to generalize the option support so that more than DNS and router options could be set.

**Comment by Zuldan** [comment]
@iainbrighton and @PlagueHO. I agree, the current naming is not correct and needs to be changed. Just add note to readme.md to say there is a breaking change and be done with it ;-)

While we're on the topic of DHCP scope options... Many enterprise vendors use customised scope options to assist with auto provisioning of devices.

The example below is used to configure auto provisioning for HP Enterprise access points. Unfortunately I haven't converted it to Powershell yet. If your developing the DHCP scope option resource further, please keep this type of customisation in mind.

netsh dhcp server add class Colubris "Vendor Class for Colubris Products" Colubris-AP 1
netsh dhcp server add optiondef 1 MSC IPADDRESS 1 vendor=Colubris comment="List of MSC IP addressess"
netsh dhcp server set optionvalue 1 IPADDRESS vendor=Colubris 192.168.1.100

-> What does it do? When you plug a HP AP into the network it looks for the custom dhcp scope options above which direct it to the provisioning server is (192.168.1.100).

**Comment by roberteckdale** [comment]
@iainbrighton and @PlagueHO @Zuldan. I know this has already been said three times but I'm going add my comment for emphasis. I agree, the current naming is absolutely incorrect and should be changed.
@Zuldan . I too would like to see support for DHCP scope options. While useful as it is, without support for DHCP scope options a significant portion of the DHCP server configuration is simply untouched.

The other item that IMHO is a necessity is the scope address pool.

**Comment by PlagueHO** [comment]
@roberteckdale  - I'm definitely still in favor of renaming the resource. But as it would be a breaking change, is a PR with such a change going to be accepted (assuming it is made very clear in the documentation that this is a breaking change)? If we could get a feel from the MSFT team ( @KarolKaczmarek, @HemantMahawar ) whether or not this might go through then I'd say it should be made.

I myself have many configs depending on this resource and I'm more than happy to update them all should this change be made.

**Comment by KarolKaczmarek** [comment]
I think we should rename it even though it's a breaking change, we just need to document it in version history and increase the major number of the version. It's better to do it now while we are still in the experimental phase for this module. Pinged @HemantMahawar to get his feedback as well.

**Comment by TravisEz13** [comment]
@PlagueHO  @iainbrighton  Just to be clear, what is the proposed rename here?
The current resource I see mentioned is xDhcpServerOption ( I agree is mis-named,) and a suggestion of xDhcpServerScopeOption?

**Comment by PlagueHO** [comment]
@TravisEz13 - good question. I actually think perhaps xDhcpOption?

This is because DHCP Options can actually be applied to Servers,Scopes,Policies and Reservations.

At the moment the resource will only apply to Scopes and Server options, but I can see it might be applied to Policies and Reservations down the track - and renaming it again would be even more of a PITA.

Although I'm not 100% happy with xDhcpOption either as the name implies changing general settings to the DHCP server.

Any other opinions? @KarolKaczmarek, @HemantMahawar, @TysonJHayes, @iainbrighton ?

**Comment by TravisEz13** [comment]
@PlagueHO Another option would be to have an option sub-class on the xDhcpScope resource and just consider it to be part of the 'scope' resource, with the scope having an array of these option instances

**Comment by iainbrighton** [comment]
@TravisEz13 @PlagueHO Care to elaborate on how you would see this implemented? Something like this?
```
[Write, ValueMap{"Server", "Scope","Policy","Reservation"},Values{"Server", "Scope","Policy","Reservation"}] String ScopeOption;
```
The Policy and Reservation options could be added later without breaking the schema.

**Comment by PlagueHO** [comment]
@iainbrighton - I hadn't thought too far ahead on this, but yes, something like that looks right - except the name ScopeOption would be different I think. A name like DHCPOptionType might be better.

However, one possible problem with this "combined" implementation is that each DHCPOptionType requires a different set of Keys. E.g. Server requires only the Option number, but Reservation requires a Reservation Scope Id, Client ID (MAC) and option number. They would all need to be Key's but of course that isn't possible because DSC doesn't support dynamic Keys.

So perhaps this combined approach might not actually work?

**Comment by gordonbondon** [comment]
How about utilizing composite resources? 

For example we can have **DHCPOption** resource that has parameters for all option types (PolicyName, ReserverdIP, ScopeID, Server if no other type is specified), and OptionID and Value (we will have to ditch Router, DNSDomainm DNSServer parameters and only use option ids). This resource will use Get-DhcpServerv4OptionDefinition to get option's Type, MultiValued so we can run specific validation on supplied parameters. 

We can probably add something like OptionValueType, OptionName, MultiValued, VendorClass, UserClass parameters so it is possible to create new option definition if such definition does not exist.

Then we will have DHCPServerOption, DHCPReservationOption etc. composite resources to configure specific type of options.

**Comment by PlagueHO** [comment]
@gordonbondon - that could be an interesting solution. I've not really considered the possibility of using composite resources before. But seems like it should be worth looking into further. Any chance you could flesh out a bit more detail? I'd have a go myself but I've got a bunch of other DSC work to get through.

**Comment by gordonbondon** [comment]
@PlagueHO I'll try to slap together something basic to see if this works. Not sure such concept wont be affected by issue with different keys needed you've mentioned above.

Other idea I was thinking about: move Get, Set, Test implementation with all possible parameters to separate helper module. Than dot sourcing it in resources and from resource functions calling them only with appropriate parameters. That way we can have resources with unique keys and we won't need implement everything four times for every type.

**Comment by Zuldan** [comment]
Looking forward to this guys. Not being able to configure custom scope options is a pain in the ass. VOIP handsets need like 5+ scope options.

**Comment by joe-carter** [comment]
Was there ever any development on this?  Specifically, the ability manage server level options, defining custom options and creating policies.

**Comment by marciorschneider** [comment]
Hello, I'm working on a xDhcpOption to manage the full DHCP options.

**Comment by johlju** [comment]
@PlagueHO Will the PR #39 solve this issue?

**Comment by PlagueHO** [comment]
It was actually an easy one to implement, but my problem was that the whole structure of the resources in this repo really don't align well with how DHCP Server works. I was never happy with this, which is why I didn't progress with it.

In short, MSFT_xDhcpServerOption should have been used to set Server level options - but it is used to set Scope level options which is terribly misleading. There is also no way to set Reservation level options either (although that is an edge case).

IMHO we should correct this with a breaking change that renamed MSFT_xDhcpServerOption -> MSFT_xDhcpServerScopeOption and then we could add a new resource MSFT_xDhcpServerOption and MSFT_xDhcpServerReservationOption.

I  toyed with the other method of making MSFT_xDhcpServerOption set Server, Scope and Reservation options, but I can't make that work because we'd end up with 3 keys (OptionId, ScopeId and ReservationIP) - 2 of which could be empty - which would not be acceptable.

**Comment by johlju** [comment]
I'm good with that, renaming MSFT_xDhcpServerOption -> MSFT_xDhcpServerScopeOption, and adding the two new resources.

I remove the 'in progress' label on this in the mean time until someone runs with this.

**Comment by johlju** [comment]
@PlagueHO Many thanks for the detailed answer!

**Comment by PlagueHO** [comment]
Good idea about removing the in progress. It might be something I could get to work on. I'd like to begin cleaning up this module in my spare time.

**Comment by johlju** [comment]
And I will review if you do 😃

**Comment by marciorschneider** [comment]
Hi folks, I'm working on a new resource called "MSFT_xDhcpServerOptionValue" that will implement the full "Set-DhcpServerv4OptionValue" cmdlet, so we can define any ID option in the server, scope, reservation or policy scope.

**Comment by johlju** [comment]
@marciorschneider that is great! Could you post the schema.mof here?

**Comment by johlju** [comment]
Thanks! A suggestions is that we make `Ensure` have the qualifier type `Write` and has the default value `Present`. 

Question, the properties `UserClass`, `ScopeId`, `PolicyName` and `ReservedIp` has a description that they should not be used together with other properties, but since they are key's the properties are not able to be left out from the configuration. How should we think here?

**Comment by PlagueHO** [comment]
This was the same challenge I came across when I tried to design a resource that could handle all 3 scenarios (server,scope and reserved ip). One possible solution is to do what we did in StorageDsc and use a generic id key and an idType. The idType could be server, scope or reservedip and default to scope (as this is the most common case).

**Comment by PlagueHO** [comment]
Actually thinking about this further it would have other undesirable trade-offs such as for   idtype server the id would have to be empty.

**Comment by marciorschneider** [comment]
It's a little tricky because the cmdlet can set the option at four different scopes (Server, DHCP scope, policy or reserved IP), so an option could be setted 4 times.


I've improved the description and corrected the OptionValue to be "Write", what you think?


[ClassVersion("1.0.0.0"), FriendlyName("xDhcpServerOptionValue")]
class MSFT_xDhcpServerOptionValue : OMI_BaseResource
{
    [key,        Description("Where to set the option value."),ValueMap{"Server","DhcpScope","Policy","ReservedIP"},Values{"Server","DhcpScope","Policy","ReservedIP"}] String ApplyTo;
    [Key,        Description("Option ID, specify an integer between 1 and 255.")] uint32 OptionId;
    [Write,      Description("Option data value.")] String OptionValue[];
    [Key,        Description("Vendor class. Use an empty string for default vendor class.")] String VendorClass;
    [Key,        Description("User class. If not used set it to an empty string. Will be ignored if ApplyTo is Policy.")] String UserClass;
    [Key,        Description("Scope Id. If not used set it to an empty string. Will be ignored if ApplyTo is not DhcpScope.")] String ScopeId;
    [Key,        Description("Policy name. If not used set it to an empty string. Will be ignored if ApplyTo is not Policy.")] String PolicyName;
    [Key,        Description("Reserved IP. If not used set it to an empty string. Will be ignored if ApplyTo is not ReservedIP.")] String ReservedIP;
    [Key,        Description("Class address family. Currently needs to be IPv4."), ValueMap{"IPv4"}, Values{"IPv4"}] String AddressFamily;
    [Write,      Description("Whether the DHCP option should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

**Comment by PlagueHO** [comment]
@marciorschneider , @johlju - these are all the options I started going through when I last looked at this. I really think the only one I think that has no unwanted side effects is to split it into 4 resources - with the old DhcpServerOptions one being replaced. All the other options allow invalid configurations or are counter intuitive.

**Comment by marciorschneider** [comment]
Yes, I agree that is not intuitive. Splitting it on 4 resources would be something like this:

[ClassVersion("1.0.0.0"), FriendlyName("xDhcpServerOptionValue")]
class MSFT_xDhcpServerOptionValue : OMI_BaseResource
{
    [Key,        Description("Option ID, specify an integer between 1 and 255.")] uint32 OptionId;
    [Write,      Description("Option data value.")] String OptionValue[];
    [Key,        Description("Vendor class. Use an empty string for default vendor class.")] String VendorClass;
    [Key,        Description("User class. Use an empty string for default user class.")] String UserClass;
    [Key,        Description("Class address family. Currently needs to be IPv4."), ValueMap{"IPv4"}, Values{"IPv4"}] String AddressFamily;
    [Write,      Description("Whether the DHCP option should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};



[ClassVersion("1.0.0.0"), FriendlyName("xDhcpScopeOptionValue")]
class MSFT_xDhcpScopeOptionValue : OMI_BaseResource
{
    [Key,        Description("Scope ID.")] String ScopeId;
    [Key,        Description("Option ID, specify an integer between 1 and 255.")] uint32 OptionId;
    [Write,      Description("Option data value.")] String OptionValue[];
    [Key,        Description("Vendor class. Use an empty string for default vendor class.")] String VendorClass;
    [Key,        Description("User class. Use an empty string for default user class.")] String UserClass;
    [Key,        Description("Class address family. Currently needs to be IPv4."), ValueMap{"IPv4"}, Values{"IPv4"}] String AddressFamily;
    [Write,      Description("Whether the DHCP option should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};





[ClassVersion("1.0.0.0"), FriendlyName("xDhcpReservedIPOptionValue")]
class MSFT_xDhcpReservedIPOptionValue : OMI_BaseResource
{
    [Key,        Description("Scope ID.")] String ScopeId;
    [Key,        Description("Option ID, specify an integer between 1 and 255.")] uint32 OptionId;
    [Write,      Description("Option data value.")] String OptionValue[];
    [Key,        Description("Vendor class. Use an empty string for default vendor class.")] String VendorClass;
    [Write,      Description("User class.")] String UserClass;
    [Key,        Description("Class address family. Currently needs to be IPv4."), ValueMap{"IPv4"}, Values{"IPv4"}] String AddressFamily;
    [Write,      Description("Whether the DHCP option should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};





[ClassVersion("1.0.0.0"), FriendlyName("xDhcpPolicyOptionValue")]
class MSFT_xDhcpPolicyOptionValue : OMI_BaseResource
{
    [Key,        Description("Scope ID. Use an empty string to apply at server level and not scope level.")] String ScopeId;
    [Key,        Description("Option ID, specify an integer between 1 and 255.")] uint32 OptionId;
    [Key,        Description("Policy Name")] String PolicyName;
    [Write,      Description("Option data value.")] String OptionValue[];
    [Key,        Description("Vendor class. Use an empty string for default vendor class.")] String VendorClass;
    [Key,        Description("Class address family. Currently needs to be IPv4."), ValueMap{"IPv4"}, Values{"IPv4"}] String AddressFamily;
    [Write,      Description("Whether the DHCP option should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

**Comment by johlju** [comment]
@marciorschneider @PlagueHO To me the 4 resource proposals that @marciorschneider made in the previous comment looks promising. I agree that 4 resources is the way to go. I don't have the full knowledge to determine if this replaces xDhcpServerOption (it looks like it is hard-coded to set DNS and gateway for a scope). But if you agree that the 4 resource above makes xDhcpServerOption obsolete, then we should either remove this in the PR or add an issue to remove it once the other resources are merged. 

@marciorschneider Would you like to run with this to create 4 resources? It would be good if they could share code (helper functions) so that code is not duplicated where possible.

**Comment by marciorschneider** [comment]
Hello folks, I wrote the 4 resources. May you please review it, @johlju? Thanks!

**Comment by johlju** [comment]
@marciorschneider Awesome! Will do!
