### ISSUE TITLE
Test-DscConfiguration always returns false on DnsServerIPAddress and DnsDomain 

### ISSUE THREAD

**Issue by jmarkert** [PowerShell/xDhcpServer#14]
I'm trying to set the DNS-Domain and DNS-Server Adresse with the xDhcpServerOption resource, but the test always returns false

I'm working with Windows 10 and PS v5 ProductionPreview on Server 2012r2

```powershell
AUSFÜHRLICH: [WIN-DC1]:                            [[xDhcpServerOption]192.168.18.0] Checking Dns server ip option ...
AUSFÜHRLICH: [WIN-DC1]:                            [[xDhcpServerOption]192.168.18.0] DNS server ip is not correct. Expected System.String[], actual
AUSFÜHRLICH: [WIN-DC1]:                            [[xDhcpServerOption]192.168.18.0] Setting DNS server ip option ...
AUSFÜHRLICH: [WIN-DC1]:                            [[xDhcpServerOption]192.168.18.0] DNS server ip option is set to System.String[].
AUSFÜHRLICH: [WIN-DC1]:                            [[xDhcpServerOption]192.168.18.0] Checking Dns domain name option ...
AUSFÜHRLICH: [WIN-DC1]:                            [[xDhcpServerOption]192.168.18.0] DNS domain name is not correct. Expected lab.local, actual
AUSFÜHRLICH: [WIN-DC1]:                            [[xDhcpServerOption]192.168.18.0] Setting DNS domain name option ...
AUSFÜHRLICH: [WIN-DC1]:                            [[xDhcpServerOption]192.168.18.0] DNS domain name option is set to lab.local.


AUSFÜHRLICH: [WIN-DC1]:                            [[xDhcpServerOption]192.168.18.0] Checking Dns server ip option ...
AUSFÜHRLICH: [WIN-DC1]:                            [[xDhcpServerOption]192.168.18.0] DNS server ip is not correct. Expected System.String[], actual
AUSFÜHRLICH: [WIN-DC1]: LCM:  [ BeendenTesten   ]  [[xDhcpServerOption]192.168.18.0] False in 0.1560 Sekunden.
```

here is the conf:
```powershell
xDhcpServerOtion '192.168.18.0'
{
    ScopeID = '192.168.18.0'
    AddressFamily = 'IPv4'
    Router = '192.168.18.4'
    DnsDomain = 'lab.local'
    DnsServerIPAdress = '192.168.18.18','192.168.18.37'
    Ensure = 'Present'
}
```

**Comment by iainbrighton** [comment]
@jmarkert @TravisEz13 I'll test and fix this along with #2 as soon as I get the chance!

**Comment by iainbrighton** [comment]
@jmarkert I cannot recreate this issue on WMF 4 or WMF 5. I have, however, fixed the verbose output in the PR for #2. Perhaps you can try this when @TravisEz13 merges the changes in?

**Comment by iainbrighton** [comment]
@jmarkert The changes have been merged into the dev branch. Can you try this out and let me know what happens? Thx

**Comment by jmarkert** [comment]
@iainbrighton 
Sorry for the delay, I'm now on module version 1.3 but it's still not working.
I found the reason: the value names are localized so on my german 2012r2 it's 'DNS-Server' an 'DNS-Domänenname'

e.g. MSFT_xDhcpServerOption.psm1 line 262:
$dnsServerIP = ($dhcpOption | Where-Object Name -like 'DNS Servers').value 

I guess a solution would be to select the OptionValue by OptionId.

**Comment by iainbrighton** [comment]
Yeah - that would certainly resolve the issue! I'll fix send a PR with this change. I've no idea why some settings were implemented by OptionId and some not!
