### ISSUE TITLE
LeaseDuration Bug - Incorrect duration set

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xDhcpServer#21]
If I set Lease Duration to '02:00:00' then on the DHCP server that translates to

"Days: 0 Hours: 2 Minutes: 0"

If I set Lease Duration to '48:00:00' then on the DHCP server that translates to 

Days: 48 Hours: 0 Minutes: 0

**Comment by iainbrighton** [comment]
@Zuldan This is an issue in the .Net timespan conversion. The timespan should specified as `Days:Hours:Minutes:Seconds'. If you're trying to set 2 days, you'll need to use '02:00:00:00'.

I'll update the documentation.

**Comment by TravisEz13** [comment]
I left a comment on PR #22 suggesting we add a function to convert a timespan to this format.  This would help.

**Comment by Zuldan** [comment]
@TravisEz13, the lease should be taking in a timespan (as does the dhcp cmdlet), I'm not sure why the DHCP resource has to be a different format from the DHCP cmdlet.

**Comment by TravisEz13** [comment]
@Zuldan Let me investigate if Timespan is a natively supported CIM type.  I suspect it is not and that is why this implementation was chosen.

**Comment by Zuldan** [comment]
@iainbrighton, thanks for the tip, it worked!

**Comment by Zuldan** [comment]
@TravisEz13 , thank you for investigating. Interested to hear what you find.
