### ISSUE TITLE
Feature Request - Authorization

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xDhcpServer#8]
Hi Team, at the moment the xDhcpServer resource cannot create a functioning DHCP server because authorization is required for the DHCP server to start serving DHCP requests. As a work around I've created a script resource. It would be nice if xDhcpServer could authorize as well.

        Script AuthorizeDHCPServer
        {
            DependsOn   = '[Service]DHCPService'
            PsDscRunAsCredential = $Credential
            GetScript = {
                @{
                    GetScript = $GetScript
                    SetScript = $SetScript
                    TestScript = $TestScript
                    Result = $null -ne (Get-DhcpServerInDC | Where-Object -FilterScript {$PSItem.DnsName -like "$($Using:Node.NodeName)*"})
                }           
            }
            
            SetScript = {
                Add-DhcpServerInDC -DnsName "$($Using:Node.NodeName).$($Using:FQDN)"
            }

            TestScript = {
                $Status = $null -ne (Get-DhcpServerInDC | Where-Object -FilterScript {$PSItem.DnsName -like "$($Using:Node.NodeName)*"})
                $Status -eq $True
            }
        }

**Comment by iainbrighton** [comment]
I have working 'xDhcpServerActivation' resource for this. Just working on some Pester tests and documentation before pushing. You can find it here: https://github.com/iainbrighton/xDhcpServer if you want to give a test?

**Comment by PlagueHO** [comment]
Hi @iainbrighton,
your xDHCPServerActivation has a cmdlet that isn't available (or at least I can't find it anywhere): Get-ValidIPAddress. I'm not sure of the purpose of this cmdlet and not sure it is necessary.

Also, it might be worth sticking to the recommended term "Authorize" DHCP Server rather than Activate -it might get confused with Activating a scope.

And finally, most of the time I'd want to have a DHCP server Authorize/Unauthorize itself without using any parameters at all (in which case it uses the current machine DNS and IP Addresses). In this case I wouldn't even want to specify an IP Address or DNS Address parameter - it would be awesome if the only parameter required was Ensure.

That would be my wishlist for this resource :)

**Comment by iainbrighton** [comment]
Thanks @PlagueHO for the feedback!

1. The Get-ValidIPAddress method is in the \DSCResources/Helper.psm1 file and validates that the given IP address is an actual/valid address.
2. I'm happy to change the name of the resource. Should it be changed it to xDhcpServerAuthorization or xDhcpServerAuthorize?
3. The IPAddress and Server properties are required by the underlying AD cmdlet. I see no harm in defaulting them to the server's FQDN and first enumerated IP address. That way they can still be overridden (if required) and activation enabled from another host.

Sound good?
Iain

**Comment by PlagueHO** [comment]
Hi @iainbrighton,

1. Oh wow, I searched everywhere for the Get-ValidIPAddress and never thought to look in Helper.psm1 :) Good to know!
2. I'm thinking xDHCPServerAuthorize but both make sense.
3. I think these parameters are optional for the Add-DHCPServerInDC cmdlet (see https://technet.microsoft.com/en-us/library/jj590712%28v=wps.630%29.aspx). If they aren't passed the cmdlet automatically defaults them I think. But it would be great if I didn't have to set the IP address and DNS FQDN as parameters (unless I wanted to) in the DSC config. I could of course, but in most cases just calling Add-DHCPServerInDC with no parameters does everything right. I'm also being lazy and trying to avoid passing additional info to the DSC config :)

Hope that makes sense!

**Comment by Zuldan** [comment]
Hi Iain, thanks for taking time to add this feature. 

2. I agree with PlagueHO, xDHCPServerAuthorize is my preference

Please be aware, there is a chance a DHCP server can be in the AD DHCP Server database by just "hostname" OR "FQDN". That is why I had to use "-like" in my script to capture all forms of the server DNS name. I'm not sure why some servers are different to others but I can tell you in large DHCP environment it happens.

Get-DhcpServerInDC | Where-Object -FilterScript {$PSItem.DnsName -like "$($Using:Node.NodeName)*"}

On another note, if I could bring your attention to this xDHCP feature request - https://github.com/PowerShell/xDhcpServer/issues/7. Do you have the time to add this feature? It should be pretty easy to implement. All the Powershell cmdlets required are inbuilt, they just need a resource built around them.
