### ISSUE TITLE
LeaseDuration is currently mandatory

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xDhcpServer#9]
The xDhcpServerScope actually requires the LeaseDuration property to be defined or the resource execution fails, but the configuration doesn't  enforce this.
- The LeaseDuration property should be marked as 'Required' in the schema.mof
- Default the LeaseDuration to "00:08:00" (my preferred option).

**Comment by PlagueHO** [comment]
IMHO I'd want to go with your preferred option (default the LeaseDuration).

**Comment by dcrreynolds** [comment]
If we add a simple if($LeaseDuration) around the get-validTimeSpan in the test it will be possible to leave LeaseDuration empty. This will not change the lease duration of any existing scopes and will default to the standard 8 days when creating a new scope. I don't think leaving a non-mandatory value blank should force the configuration to use a default value if the scope already exist.

**Comment by TravisEz13** [comment]
The issue was fixed.  We still need a test to make sure the issue does not regress.

**Comment by iainbrighton** [comment]
@TravisEz13 I'll add a test or two and update to the latest test template...
